const colors = require("tailwindcss/colors");
const plugin = require("tailwindcss/plugin");

module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        current: "currentColor",
        primary: "#fdc6bf",
        accentPrimary: "#f5d9d8",
        accentSecondary: "#fcf7fb",
        dark: "#748899",
        darkAccent: "#a0a9b0",
        light: "#f9f9ed",
        white: "#ffffff",
        black: "#000000",
        secondary: "#f5cee8",
      },
      fontFamily: {
        overlock: ["Overlock"],
      },
      minWidth: {
        titleImageMedium: "20vw",
        sortDropdown: "8rem",
        96: "24rem",
      },
      maxWidth: {
        screenImageLarge: "960px",
        screenImageMedium: "768px",
        titleImageMedium: "24rem",
        titleImageLarge: "32rem",
        96: "24rem",
      },
      maxHeight: {
        screenImageLarge: "540px",
        screenImageMedium: "432px",
        titleImageMedium: "24rem",
        titleDetailsContainer: "32rem",
        titleDetailsDescription: "20rem",
      },
      minHeight: {
        titleImageMedium: "16rem",
        titleDetailsContainer: "32rem",
        titleDetailsDescription: "20rem",
        44: "11rem",
        56: "14rem",
        96: "24rem",
        vh25: "25vh",
        vh50: "50vh",
        vh75: "75vh",
      },
      width: {
        titleImageMedium: "20rem",
        titleImageLarge: "32rem",
        32: "8rem",
      },
      height: {
        88: "22rem",
      },
      borderWidth: {
        veryThin: "0.5px",
      },
      gridTemplateColumns: {
        16: "repeat(16, minmax(0, 1fr))",
        normalScreen: "repeat(5, 208px)", // 208 px/13 rem for w-52 card
      },
      margin: {
        titleImageMedium: "-8rem",
      },
      width: {
        100: "25rem",
        104: "26rem",
        112: "28rem",
        116: "29rem",
        120: "30rem",
        124: "31rem",
        128: "32rem",
        144: "36rem",
        200: "50rem",
        208: "52rem",
        216: "54rem",
        240: "60rem",
        248: "62rem",
        256: "64rem",

        280: "70rem",
        320: "80rem",
        328: "82rem",
        336: "84rem",
      },
      spacing: {
        px: "1px",
        0: "0px",
        0.5: "0.125rem",
        1: "0.25rem",
        1.5: "0.375rem",
        2: "0.5rem",
        2.5: "0.625rem",
        3: "0.75rem",
        3.5: "0.875rem",
        4: "1rem",
        5: "1.25rem",
        6: "1.5rem",
        7: "1.75rem",
        8: "2rem",
        9: "2.25rem",
        10: "2.5rem",
        11: "2.75rem",
        12: "3rem",
        14: "3.5rem",
        16: "4rem",
        20: "5rem",
        24: "6rem",
        28: "7rem",
        32: "8rem",
        36: "9rem",
        40: "10rem",
        44: "11rem",
        48: "12rem",
        52: "13rem",
        56: "14rem",
        60: "15rem",
        64: "16rem",
        72: "18rem",
        80: "20rem",
        96: "24rem",
      },
      borderWidth: {
        3: "3px",
      },
      transformOrigin: {
        center: "center",
        top: "top",
        "top-right": "top right",
        right: "right",
        "bottom-right": "bottom right",
        bottom: "bottom",
        "bottom-left": "bottom left",
        left: "left",
        "top-left": "top left",
      },
      objectPosition: {
        bottom: "bottom",
        center: "center",
        left: "left",
        "left-bottom": "left bottom",
        "left-top": "left top",
        right: "right",
        "right-bottom": "right bottom",
        "right-top": "right top",
        top: "top",
      },
      backgroundPosition: {
        bottom: "bottom",
        center: "center",
        left: "left",
        "left-bottom": "left bottom",
        "left-top": "left top",
        right: "right",
        "right-bottom": "right bottom",
        "right-top": "right top",
        top: "top",
      },
      inset: {
        44: "11rem",
      },
    },
  },
  variants: {
    extend: {
      width: ["hover"],
      height: ["hover"],
    },
  },
  plugins: [
    require("@tailwindcss/forms"), // import tailwind forms
  ],
};
